version 2.18.1

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3,8 +3,8 @@
 #set -o errexit
 #set -v
 
-#wwwHome=openmx.psyc.virginia.edu
-wwwHome=openmx.ssri.psu.edu/software
+#wwwHome=openmx.ssri.psu.edu/software
+wwwHome=vipbg.vcu.edu/vipbg/OpenMx2/software
 
 isdef() {
     tmp1=/tmp/openmx.$$.cpp
@@ -36,10 +36,10 @@ else
 fi
 
 : ${R_HOME:=`R RHOME`}
-if test -z "${R_HOME}"; then 
-   echo "could not determine R_HOME" 
-   exit 1 
-fi 
+if test -z "${R_HOME}"; then
+   echo "could not determine R_HOME"
+   exit 1
+fi
 
 devmode=0
 if [ -f .devmode ]; then
@@ -78,11 +78,11 @@ if [ "$cxx_type" = gcc ]; then
 	if version_ge $cxx_version 5.0; then
 	    COMPILER_CXXFLAGS="$COMPILER_CXXFLAGS -fdiagnostics-color=auto -DEXTRA_GCC_DIAG -Wno-misleading-indentation -Wno-pragmas -Wno-ignored-attributes"
 	    COMPILER_LDFLAGS="$COMPILER_LDFLAGS"
-	    xcheck_CXXFLAGS="-fsanitize=undefined -fno-omit-frame-pointer"
+	    xcheck_CXXFLAGS="-fsanitize=undefined"
 	    xcheck_LDFLAGS="-fsanitize=undefined"
 	fi
 	if version_ge $cxx_version 6.0; then
-	    COMPILER_CXXFLAGS="$COMPILER_CXXFLAGS -Wno-misleading-indentation"
+	    COMPILER_CXXFLAGS="$COMPILER_CXXFLAGS -Wno-misleading-indentation -Wreorder"
 	fi
 	if version_ge $cxx_version 7.0; then
 	    COMPILER_CXXFLAGS="$COMPILER_CXXFLAGS -Wno-int-in-bool-context"
@@ -124,9 +124,9 @@ if [ ! -f inst/no-npsol ] && [ -r inst/npsol/checksum ]; then
 	    npsol_url1="http://$wwwHome/packages/npsol/linux/${omx_arch}/$want"
 	    npsol_url2="http://$wwwHome/packages/npsol/$pick/libnpsol.a"
 	    if [ ! -f src/libnpsol.a ]; then
-		wget -q -O src/libnpsol.a "$npsol_url1" || true
+		wget -O src/libnpsol.a "$npsol_url1" || true
 		if grep -s 'HTML document' src/libnpsol.a; then
-		    wget -q -O src/libnpsol.a "$npsol_url2" || true
+		    wget -O src/libnpsol.a "$npsol_url2" || true
 		fi
 	    fi
 	    got=`sha1sum src/libnpsol.a | cut -f1 -d' '`
@@ -150,8 +150,6 @@ if [ ! -f inst/no-npsol ] && [ -r inst/npsol/checksum ]; then
 	    ;;
 	*Darwin)
 	    omx_os=osx
-	    arch_LDFLAGS="-mmacosx-version-min=10.7"
-	    arch_CXXFLAGS="-mmacosx-version-min=10.7"
 	    npsol_library="inst/npsol/osx"
 	    ;;
 	*)
@@ -195,8 +193,8 @@ echo "xcheck_LDFLAGS=$xcheck_LDFLAGS" >> src/Makevars.new
 
 # check for special environment variables
 if [ "x$IMX_SAFE" = x1 ]; then
-    echo 'DEBUG_CXXFLAGS=`xcheck_CXXFLAGS` -UNDEBUG -DOMX_BOUNDS_CHECK -D_GLIBCXX_DEBUG' >> src/Makevars.new
-    echo 'DEBUG_LDFLAGS=`xcheck_LDFLAGS`' >> src/Makevars.new
+    echo 'DEBUG_CXXFLAGS=$(xcheck_CXXFLAGS) -UNDEBUG -DOMX_BOUNDS_CHECK -D_GLIBCXX_DEBUG' >> src/Makevars.new
+    echo 'DEBUG_LDFLAGS=$(xcheck_LDFLAGS)' >> src/Makevars.new
 elif [ "x$IMX_GCOV" = x1 ]; then
     # To collect gcov statistics (gcc only)
     echo 'DEBUG_CXXFLAGS=--coverage' >> src/Makevars.new
